[default]
# address = "0.0.0.0"
limits = { form = "64 kB", json = "1 MiB" }
# 加密秘钥 用于cookie的私有加密解密
secret_key = "6d51dcfb7899438abc8eaa4530123a5249gfac9b9b45"
# 暂时目标表
temp_dir = "/tmp"
## 仅在调试模式下编译时设置, `cargo build`
[debug]
# 启动端口
port = 8200
## 只有“default”中的“json”键将被覆盖`表单`将保留
limits = { json = "10MiB" }
# 运行的目标地址
address = "127.0.0.1"


## 仅在发布模式下编译时设置 `cargo build --release`
[release]

port = 8080
ip_header = false

[default.databases.rusqlite]
# url = "file:rusqlite?mode=memory&cache=shared"
url = "./test.db"
